services:
  django-crm:
    container_name: SNAIL_SLICE_CRM
    build: .
    command: gunicorn SnailCRM.wsgi --bind=0.0.0.0:8080
    volumes:
      - .:/usr/src/crm
    ports:
      - 8080:8080
    env_file:
      - .env

