# Generated by Django 4.2.16 on 2024-09-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlasticType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "manufacturer",
                    models.CharField(max_length=50, verbose_name="Производитель"),
                ),
                (
                    "link",
                    models.URLField(
                        default="https://rec3d.ru/", verbose_name="Ссылка на товар"
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Тип")),
                ("color", models.CharField(max_length=50, verbose_name="Цвет")),
                (
                    "diameter",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Диаметр"
                    ),
                ),
                ("wps", models.IntegerField(verbose_name="Вес катушки, г")),
                ("price", models.IntegerField(verbose_name="Цена, руб.")),
                (
                    "spools_in_stock",
                    models.IntegerField(default=0, verbose_name="Катушки в наличии"),
                ),
                (
                    "weight_in_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="Вес в наличии, г",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип пластика",
                "verbose_name_plural": "Типы пластика",
            },
        ),
        migrations.CreateModel(
            name="Models3D",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("link", models.URLField(verbose_name="Модель")),
                (
                    "file3mf",
                    models.FileField(upload_to="files/", verbose_name="Модель .3mf"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Вес"
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Маржинальность, %"
                    ),
                ),
                (
                    "test_print",
                    models.BooleanField(default=False, verbose_name="Тестовая печать"),
                ),
                (
                    "photo",
                    models.ImageField(
                        default="logo.png", upload_to="photos/", verbose_name="Фото"
                    ),
                ),
                (
                    "zip_photo",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/zip/",
                        verbose_name="Архив с фото",
                    ),
                ),
                ("marketplace_link", models.URLField(verbose_name="Маркетплейс")),
                (
                    "plastic_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CRM.plastictype",
                        verbose_name="Тип пластика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель на печать",
                "verbose_name_plural": "Модели на печать",
            },
        ),
    ]
