# Generated by Django 4.2.16 on 2024-09-27 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models3D',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на модель')),
                ('file3mf', models.FileField(upload_to='files/', verbose_name='Модель .3mf')),
                ('weight', models.FloatField(verbose_name='Вес, г')),
                ('revenue', models.FloatField(verbose_name='Наценка, %')),
                ('test_print', models.BooleanField(default=False, verbose_name='Тестовая печать')),
                ('photo', models.ImageField(default='logo.png', upload_to='photos/', verbose_name='Фото')),
                ('zip_photo', models.FileField(blank=True, null=True, upload_to='photos/zip/', verbose_name='Архив с фото')),
                ('marketplace_link', models.URLField(blank=True, default=None, verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Модель на печать',
                'verbose_name_plural': 'Модели на печать',
            },
        ),
        migrations.CreateModel(
            name='PlasticType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
                ('link', models.URLField(default='https://rec3d.ru/', verbose_name='Ссылка на товар')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('color', models.CharField(choices=[('black', 'черный'), ('red', 'красный'), ('brown', 'коричневый'), ('orange', 'оранжевый'), ('white', 'белый'), ('green', 'зеленый'), ('blue', 'синий'), ('crimson', 'малиновый'), ('darkolivegreen', 'оливковый'), ('cyan', 'бирюзовый'), ('sliver', 'серебристый'), ('gold', 'золотоый'), ('aqua', 'голубой'), ('purple', 'фиолетовый'), ('beige', 'бесцветный')], max_length=50, verbose_name='Цвет')),
                ('diameter', models.FloatField(choices=[(1.75, '1.75'), (2.85, '2.85')], verbose_name='Диаметр, мм')),
                ('wps', models.IntegerField(verbose_name='Вес катушки, г')),
                ('price', models.IntegerField(verbose_name='Цена, руб.')),
                ('spools_in_stock', models.IntegerField(default=0, verbose_name='Катушки в наличии, шт')),
                ('weight_in_stock', models.FloatField(default=0, verbose_name='Вес в наличии, г')),
            ],
            options={
                'verbose_name': 'Тип пластика',
                'verbose_name_plural': 'Типы пластика',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Модель принтера')),
                ('diameter', models.FloatField(choices=[(1.75, '1.75'), (2.85, '2.85')], verbose_name='Диаметр, мм')),
                ('price', models.IntegerField(verbose_name='Цена, руб.')),
                ('lifetime', models.IntegerField(verbose_name='Срок жизни, лет')),
                ('expences', models.IntegerField(verbose_name='Стоимость часа работы, руб.')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.models3d', verbose_name='Модель')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='CRM.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Заказ на печать',
                'verbose_name_plural': 'Заказы на печать',
            },
        ),
        migrations.AddField(
            model_name='models3d',
            name='plastic_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.plastictype', verbose_name='Тип пластика'),
        ),
    ]
