# Generated by Django 4.2.16 on 2024-09-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="models3d",
            name="zip_photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="photos/zip/",
                verbose_name="Архив с фото",
            ),
        ),
    ]
