# Generated by Django 4.2.16 on 2024-09-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRM", "0002_alter_models3d_zip_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="models3d",
            name="link",
            field=models.URLField(verbose_name="Ссылка на модель"),
        ),
        migrations.AlterField(
            model_name="models3d",
            name="marketplace_link",
            field=models.URLField(blank=True, default=None, verbose_name="Маркетплейс"),
        ),
        migrations.AlterField(
            model_name="models3d",
            name="revenue",
            field=models.FloatField(verbose_name="Маржинальность, %"),
        ),
        migrations.AlterField(
            model_name="models3d",
            name="weight",
            field=models.FloatField(verbose_name="Вес"),
        ),
        migrations.AlterField(
            model_name="plastictype",
            name="color",
            field=models.CharField(
                choices=[
                    ("black", "черный"),
                    ("red", "красный"),
                    ("brown", "коричневый"),
                    ("orange", "оранжевый"),
                    ("white", "белый"),
                    ("green", "зеленый"),
                    ("blue", "синий"),
                    ("crimson", "малиновый"),
                    ("darkolivegreen", "оливковый"),
                    ("cyan", "бирюзовый"),
                    ("sliver", "серебристый"),
                    ("gold", "золотоый"),
                    ("aqua", "голубой"),
                    ("purple", "фиолетовый"),
                    ("beige", "бесцветный"),
                ],
                max_length=50,
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="plastictype",
            name="diameter",
            field=models.FloatField(
                choices=[(1.75, "1.75"), (2.85, "2.85")], verbose_name="Диаметр"
            ),
        ),
        migrations.AlterField(
            model_name="plastictype",
            name="weight_in_stock",
            field=models.FloatField(default=0, verbose_name="Вес в наличии, г"),
        ),
    ]
