# Generated by Django 4.2.16 on 2024-09-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_models3d_link_alter_models3d_marketplace_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models3d',
            name='weight',
            field=models.FloatField(verbose_name='Вес, г'),
        ),
    ]
