# Generated by Django 4.2.16 on 2024-09-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_models3d_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Модель принтера')),
                ('diameter', models.FloatField(choices=[(1.75, '1.75'), (2.85, '2.85')], verbose_name='Диаметр, мм')),
                ('price', models.IntegerField(verbose_name='Цена, руб.')),
                ('lifetime', models.IntegerField(verbose_name='Срок жизни, лет')),
                ('expences', models.IntegerField(verbose_name='Стоимость часа работы, руб.')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.AlterField(
            model_name='plastictype',
            name='diameter',
            field=models.FloatField(choices=[(1.75, '1.75'), (2.85, '2.85')], verbose_name='Диаметр, мм'),
        ),
        migrations.AlterField(
            model_name='plastictype',
            name='spools_in_stock',
            field=models.IntegerField(default=0, verbose_name='Катушки в наличии, шт'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.models3d', verbose_name='Модель')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='CRM.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Заказ на печать',
                'verbose_name_plural': 'Заказы на печать',
            },
        ),
    ]
