# Generated by Django 4.2.16 on 2024-09-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_printer_alter_plastictype_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models3d',
            name='revenue',
            field=models.FloatField(verbose_name='Наценка, %'),
        ),
    ]
