# Generated by Django 4.2.16 on 2024-09-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(verbose_name='ID группы')),
                ('group_name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('send_notifications', models.BooleanField(default=False, verbose_name='Отправлять уведомления')),
                ('handle_messages', models.BooleanField(default=False, verbose_name='Обрабатывать сообщения')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='TgMessageText',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='Время отправки')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('3dModelAdded', 'Добавлена новая модель'), ('photosAddedToModel', 'Добавлены фото к модели'), ('testPrintStatusChanged', 'Статус тестовой печати изменен')], max_length=255, verbose_name='Событие')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.tggroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Текст сообщения',
                'verbose_name_plural': 'Тексты сообщений',
                'unique_together': {('group', 'event')},
            },
        ),
    ]
