# Generated by Django 4.2.16 on 2024-09-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(verbose_name='ID группы')),
                ('group_name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('send_notifications', models.BooleanField(default=False, verbose_name='Отправлять уведомления')),
                ('handle_messages', models.BooleanField(default=False, verbose_name='Обрабатывать сообщения')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
