# Generated by Django 4.2.16 on 2024-09-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tgmessagetext',
            unique_together=set(),
        ),
    ]
