# Generated by Django 4.2.16 on 2024-09-27 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tggroup',
            name='group_name',
            field=models.CharField(max_length=255, verbose_name='Название группы'),
        ),
        migrations.CreateModel(
            name='TgMessageText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('3dModelAdded', 'Добавлена новая модель'), ('photosAddedToModel', 'Добавлены фото к модели'), ('testPrintStatusChanged', 'Статус тестовой печати изменен')], max_length=255, verbose_name='Событие')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.tggroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Текст сообщения',
                'verbose_name_plural': 'Тексты сообщений',
                'unique_together': {('group', 'event')},
            },
        ),
    ]
