# Generated by Django 4.2.16 on 2024-09-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_alter_tgmessagetext_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tgmessagetext',
            unique_together={('group', 'event')},
        ),
        migrations.RemoveField(
            model_name='tgmessagetext',
            name='created_at',
        ),
    ]
